//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntHill.NET.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntHill.NET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to antQueen.png.
        /// </summary>
        internal static string antQueenBmp {
            get {
                return ResourceManager.GetString("antQueenBmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to antWarrior.png.
        /// </summary>
        internal static string antWarriorBmp {
            get {
                return ResourceManager.GetString("antWarriorBmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to antWorker.png.
        /// </summary>
        internal static string antWorkerBmp {
            get {
                return ResourceManager.GetString("antWorkerBmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file is not valid. It generated exception: .
        /// </summary>
        internal static string exceptionXmlNotValid {
            get {
                return ResourceManager.GetString("exceptionXmlNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics.
        /// </summary>
        internal static string GraphicsPath {
            get {
                return ResourceManager.GetString("GraphicsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sandTile.png.
        /// </summary>
        internal static string indoorTileBmp {
            get {
                return ResourceManager.GetString("indoorTileBmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map has no indoor tiles..
        /// </summary>
        internal static string noIndoorTilesError {
            get {
                return ResourceManager.GetString("noIndoorTilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map has no outdoor tiles..
        /// </summary>
        internal static string noOutdoorTilesError {
            get {
                return ResourceManager.GetString("noOutdoorTilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grassTile.png.
        /// </summary>
        internal static string outdoorTileBmp {
            get {
                return ResourceManager.GetString("outdoorTileBmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spider.png.
        /// </summary>
        internal static string spiderBmp {
            get {
                return ResourceManager.GetString("spiderBmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stoneTile.png.
        /// </summary>
        internal static string wallTileBmp {
            get {
                return ResourceManager.GetString("wallTileBmp", resourceCulture);
            }
        }
    }
}
